### ISSUE TITLE
lock performance

### ISSUE THREAD

**Issue by Yiling-J** [Krukov/cashews#127]
I'm benchmarking my multi-backend cache framework against several similar ones, including cashews. One benchmark is concurrency call with stampede/thundering-herd/dog-piling protection. My original benchmark send 200k requests with 1000 concurrency level, my framework and aiocache stampede finish in less than 1 minute but cashews seems hang forever. So I write a simple one with asyncio.gather, but this one raise exception:
`cashews.exceptions.LockedError: Key lock:__main__:foo:uid:5884 already locked`

Is this the right way(set lock=True) to use cashews with thundering-herd protection? Simple benchmark code:
```python
import random
import redis
import asyncio
from cashews import cache

cache.setup("redis://", max_connections=100, wait_for_connection_timeout=300)


@cache(ttl=None, lock=True)
async def foo(uid):
    await asyncio.sleep(0.1)
    return uid


async def bench():
    r = redis.Redis(host="localhost", port=6379)
    r.flushall()
    await asyncio.gather(*[foo(random.randint(0, 10000)) for _ in range(5000)])


asyncio.run(bench())
```

**Comment by Krukov** [comment]
Huge Thanks for sharing it. 

I found the problem, `is_locked` function [reserved a connection](https://github.com/Krukov/cashews/blob/c9e6d393db50c7a48259805f8f8a112833861ce9/cashews/backends/redis/backend.py#L130). So 100 concurrent  `is_locked` coroutines blocking other operations including release lock (`unlock`) 

Also locking without timeout (ttl=None) was unexpected  - in this case if lock did not acquire it will raise an exception without waiting for lock release. 

Fixed in 5.3.1 


I saw your libraries for cache too, rust based memory storage is impressive, do you mind if I decided to use it too as an alternative backend ? 

And also could you please share your results of benchmarks or share the repo with code?

**Comment by Yiling-J** [comment]
> 

Great, then I can continue my benchmarks. Feel free to use Theine as your backend, my Cacheme is doing the same. 

I'm still refactoring my Cacheme, this is the results currently:

Redis GET means how many redis get command encountered and Load Hits is how many times the slow load function called.
totaly 200k requests and use a zipf generator to generate numbers. Aiocache-2 is aiocache_stampede decorator and cashews-2 is lock=True

#### 1k concurrency

|            | Time | Redis GET  | Load Hits |
|------------|------|------------|-----------|
| Cacheme    | 30 s | 166454     | 55579     |
| Aiocache   | 46 s | 200000     | 56367     |
| Aiocache-2 | 63 s | 256492     | 55417     |
| Cashews    | 51 s | 200000     | 56920     |
| cashews-2  | x    | x          | x         |

#### 100k concurrency

|            | Time  | Redis GET | Load Hits |
|------------|-------|-----------|-----------|
| Cacheme    | 30 s  | 60990     | 56782     |
| Aiocache   | 80 s  | 200000    | 125085    |
| Aiocache-2 | 178 s | 326417    | 65598     |
| Cashews    | 88 s  | 200000    | 87894     |
| cashews-2  | x     | x         | x         |

**Comment by Yiling-J** [comment]
fix confirmed, this is the result for locked cashews:
1k: redis count 200000, load count 55425, spent 137.26466012001038s
100k: redis count 200000, load count 55348, spent 236.61019372940063s

**Comment by Krukov** [comment]
Thanks for sharing
