### ISSUE TITLE
[Migration] [User experience] An exception must be raised if `cache.setup()` was not called

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Krukov/cashews#153]
## Current behavior 

If a developer will bump cashews version `4.7.1` :arrow_right: `6.2.0` then the following code 
```py
from cashews import cache

@cache(ttl=ttl)
async def func():
    ...
```
that worked in `4.7.1` will not raise an error but will stop caching silently.

## Expected behavior

In `v6.x.x` an exception must be raised if `cache.setup()` was not called.

Question: is there a single place in the code where we can quickly check this?

**Comment by Krukov** [comment]
Hi, 

To be hones I thought that exception should be raised. I found out that it is not working because of optimization - cashew do not execute cache logic if "backends" are disabled and there is a bug when there are no backends cashews think that cache is disabled .  But if call simple methods like `get` the exception `NotConfiguredError` will be raised

Also there no public api to check that cashew was setup  for now, but I gonna add it

**Comment by Krukov** [comment]
I fix this bug and added a new method - `cache.is_setup()`
