### ISSUE TITLE
Is the `cache-control` header set?

### ISSUE THREAD

**Issue by ceteri** [Krukov/cashews#156]
The async support and client-side caching here look great.

However, from testing, it appears that use of the `@cache` decorator here does not set a `cache-control` header?

Is there any reason that was omitted?

**Comment by ceteri** [comment]
When HTTP page response get cached, shouldn't there also be directives communicated to the CDN and client through `Cache-Control` headers:
<https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control>

As far as I can tell, the `@cache` decorator here does not modify FastAPI/Starlette response headers?

For example, using `@cache(ttl="30s")` should that also set a directive such as
```
Cache-Control: max-age=30
```

Handling ETags are another matter.

**Comment by ceteri** [comment]
Also, my apologies if I'm conflating the intended usage.

It has been a common practice for cache libraries on web frameworks to support both the caching strategy and the directives from the decorator. Although clearly that's not needed if the cache is used internally, not for HTTP routes.

**Comment by Krukov** [comment]
Yes, this library is framework agnostic. 

However there are some experimental functionality that's comes in 6.3.0 version  and not documented yet 

A `cashews.contrib.fastapi` module with a set of middlewares:  CacheEtagMiddleware, CacheRequestControlMiddleware, CacheDeleteMiddleware

`CacheEtagMiddleware` - will add the `Etag` + `If-None-Match` headers if cache was used during the request handle 
`CacheRequestControlMiddleware` - will handle `Cache-Control` request and response header ( properly disable cache on `Cache-Control` no-store/no-cache/max-age-0  and add Age and `Cache-Control` header if cache was used during the request handle
`CacheDeleteMiddleware` - handle `Clear-Site-Data`



@ceteri I will be happy if you will try to use it, but at your own risk because it not tested much yet ( but I think that is better then https://github.com/long2ice/fastapi-cache )))

```python
from cashews.contrib.fastapi import CacheRequestControlMiddleware

app = FastAPI()
app.add_middleware(CacheRequestControlMiddleware)

```

**Comment by Krukov** [comment]
I'll keep this issue open till I will add documentation about this "contrib" module

**Comment by ceteri** [comment]
Thank you @Krukov yes, that looks really good.
https://github.com/Krukov/cashews/blob/0b64ec98052f6dcbb3be0962ff2b8f54b96f076d/examples/fastapi_app.py#L11

Ultimately it might also be helpful to include features that take into account the edge (CDN) cache rules, and how the middleware needs to interact with those.  For example, https://developers.cloudflare.com/cache/how-to/cache-rules/  

We have not seen any caching libraries focus on the edge or intermediate storage grids used by edge caches. We've built out code to handle this, although it is not generalized in a way that it could be used readily in a framework-agnostic library.

**Comment by shijo-keyvalue** [comment]
Tried adding middleware as mentioned in the above comments : 

`app.add_middleware(CacheRequestControlMiddleware)`

But I am getting this error while starting the server.

```
...lib/python3.7/site-packages/cashews/contrib/fastapi.py", line 86, in CacheRequestControlMiddleware
    def _to_disable(cache_control_value: Optional[str]) -> tuple[Command]:
TypeError: 'type' object is not subscriptable
```

**Comment by Krukov** [comment]
Hi @shijo-keyvalue  -  Looks like a bug with python3.7 support , I will take a look at weekends. Also I found a few bugs with `CacheRequestControlMiddleware` - I gonna fix it soon, stay tuned )

**Comment by Krukov** [comment]
Added a few words in README (documentation) about contrib module and integrations/tools for an fastapi app 

@shijo-keyvalue  Sorry but I dropped 3.7 support as we don't have CI pipelines for it and it's a very "unpopular" version.
