### ISSUE TITLE
"No connection available" errors with redis-py 5.0.1

### ISSUE THREAD

**Issue by DPham-X** [Krukov/cashews#164]
There appears to be a change in how redis-py 5.0.1 does connection pooling which cashews needs to be updated with

cashews: 6.3.0
redis-py: 5.0.0 (works), 5.0.1 (broken)

Python 3.11.5(3.11.5 (main, Sep 4 2023, 15:30:52) [GCC 10.2.1 20210110])

https://github.com/redis/redis-py/issues/2995

**Comment by Krukov** [comment]
Hello, @DPham-X 

Thanks for reporting this issue,  I'll fix it soon

**Comment by Krukov** [comment]
fixed 6.40

**Comment by rkrell** [comment]
At the moment, you do not allow redis-py 5.0.1 as dependency.

But, according to https://github.com/redis/redis-py/issues/2995#issuecomment-1756493138, there is a fix needed for cashews, instead od skipping a certain redis-py version. Otherwise there won't pribably work future versions of redis-py neither.

What is the truth here?

**Comment by rkrell** [comment]
Ist this still the case with `redis==5.0.2`?

**Comment by Krukov** [comment]
Hi @rkrell  

I have tested and can confirm that the issue solved in redis==5.0.2  [Also I rerun CI with this version  ](https://github.com/Krukov/cashews/actions/runs/7878543532)

Regarding this comment https://github.com/redis/redis-py/issues/2995#issuecomment-1756493138 :
Yes cashews have an issue with closing connection on shutdown  ( and you can see warnings here https://github.com/Krukov/cashews/actions/runs/7878543532 ), but it is not so critical  and will be fixed in future ( I'll open an issue)
