### ISSUE TITLE
Minor code clean up

### ISSUE THREAD

**Issue by AIGeneratedUsername** [Krukov/cashews#26]
- [ ] Change from 
  ```python
  return await self._client.mget(keys[0], *keys[1:])
  ``` 
  to the 
  ```python
  return await self._client.mget(*keys)
  ```
---

- [ ] Change from
  ```python
  if isinstance(value, int) or value.isdigit():
     return int(value)
  ```
  to the
  ```python
  if isinstance(value, int)
      return value
  if value.isdigit():
      return int(value)
  ```

---

- [ ] Refactor magic hidden converting under the hood from microseconds to seconds based only on variable type:
 ```python
            if isinstance(expire, float):
                pexpire = int(expire * 1000)
                expire = None
 ```

- [ ] This seems to be unnecessary because on `__del__` call `self._client` will be deleted too:

   ```python
     def close(self):
        del self._client
        self._client = None
        self.__is_init = False

    __del__ = close
   ```

---

- [ ] Using `class none: pass` seems to be redundant because `None` is pickled and unpickled back. I do not understand the purpose of the 
  ```python
        value = pickle.loads(value, fix_imports=False, encoding="bytes")

        if value is none:
            return None
  ```
  because you can remove at all `class none: pass` class, and just do `return value`.

**Comment by AIGeneratedUsername** [comment]
@Krukov Could you please clarify the purpose of checking `__repr__` of unpickled data?

```python
        if self._check_repr:
            repr(value)
```
It will be great to have a comment in the code for such not obvious things.

**Comment by Krukov** [comment]
Thanks for all your suggestions and contribution 

We need to check __repr__  because we it will raise an error if structure of object have been changed. As we use pickle we can have some strange errors with cache - for example we have structure with some fields and we store it in cache
```python
@dataclasses.dataclass
class Schema:
    name: str


async def func():
    await cache.set("key", Schema("test"))

```
Than we change the schema
```python
@dataclasses.dataclass
class Schema:
    first_name: str
    last_name: str
```
And without checking repl we will have an error
```python

async def func():
    a = await cache.get("key")
    print(a.first_name)
    
>>> AttributeError: 'Schema' object has no attribute 'first_name'
```

https://github.com/Krukov/cashews#cache-invalidation-on-code-change

Regarding `mget` , I prefer to return immutable structures. I think a list comprehension in this case looks too heavy and hard to maintain and troubleshoot.

**Comment by Krukov** [comment]
Regarding the code changes: 
1) we support aioredis 1.3.x and it have this strange mget signature https://aioredis.readthedocs.io/en/v1.3.0/mixins.html#aioredis.commands.StringCommandsMixin.mget
2)  good point
3) I don't think that is bad , we just hide converting from seconds to **millisecond** because you can't use floating seconds with `ex` arg of `set` cmd with redis (https://redis.io/commands/set)
```python
await cache.set("key", "value", expire=10)  # will set ttl to 10 seconds with redis cmd "SET key value EX 10"
await cache.set("key", "value", expire=10.0)  # will also set ttl to 10 seconds "SET key value PX 10000"
```
4) I don't remember why I did it but you right
5) Thanks

**Comment by Krukov** [comment]
@AIGeneratedUsername Can I ask you for review [this PR ](https://github.com/Krukov/cashews/pull/29) ?

**Comment by AIGeneratedUsername** [comment]
By the way, it may be great to find how to make type hinting to be IDE-friendly.

![2022-02-08_09-53](https://user-images.githubusercontent.com/70140627/152943746-07561629-4210-440f-b9ab-bcb6039f53ce.png)

**Comment by AIGeneratedUsername** [comment]
@Krukov Could you please let know in a few words what is the background behind:
```python
            kwargs.setdefault("socket_keepalive", True)
```
```python
            kwargs.setdefault("socket_timeout", 0.1)
```
Why are exactly these values used? Why timeout is 0.1 and not 0.2, or 0.3, etc.
So if someone will decide to contribute, everybody will be on the same page about specific decisions under the hood.

**Comment by Krukov** [comment]
Yep, thank to point it. I hope that is no doubts about `socket_keepalive` - the same setting we have in our browsers in it set to `true`.
To be honest there is no reason why `socket_timeout` is exactly 0.1 by default. I just want to set it with a small amount based on my experience. We had an issues with cache when it stack and we got the whole app down by the end just because timeout had a big value or didn't set. I don't think that we can count the value for socket timeout, but for cache it should be extremely small just because of the purpose of cache.

 I saw some performance test with redis and they sad that average response time is 200 us ( 0.0002  sec)  ! and 100 percentile  take less then 3 ms ( 0.003 sec) (https://redis.io/topics/benchmarks) ! 
 
 Do you have some suggestions for that value?
