### ISSUE TITLE
Typing support 

### ISSUE THREAD

**Issue by Krukov** [Krukov/cashews#66]
There are lack of type annotation in library:

Expectation: 
    almost all methods should have full type annotations, enable mypy job to check typing errors

**Comment by AIGeneratedUsername** [comment]
@Krukov There must be automated CI checks that enforce developers to use the same style and type hints. I see that you use Black, Isort, Flake8, but nothing is checked at GitHub and nothing is mandatory.

There are two option: 
1. I am adding https://github.com/pre-commit/pre-commit because I've been using it for a long time and I have a ready to copy/paste config. The only problem is that I use GitLab and I will need to learn how to update CI at GitHub.
2. You will enforce Mypy, Black, Isort, Flake8 checks to make them mandatory and executed at CI automatically. 

Enabling mentioned checks will also require to apply some formatting issues, sort imports, etc. 

What is your opinion? I've started now to add and fix type hints. After I will finish with type hints, I would be happy to run Mypy at CI automatically to avoid making type hints broken in the future.

**Comment by Krukov** [comment]
Hi, 
yep, I also not so familiar with GitHub CI that is why the project have no checks for linters/formatters like black, isort and so on.
So for me any options is good,  I can enforce some rules based on my experience, but also I don't mind if you will add pre-commit. 
In general, pre-commit will be a good first step.

**Comment by AIGeneratedUsername** [comment]
Is there any reason why the `cashews.backends.interface.Backend` class is not defined as an [abstract base class (ABCs)](https://docs.python.org/3/library/abc.html)?

May I use `@abstractmethod` for the `cashews.backends.interface.Backend` class?

 I think that Mypy can not know a correct return type:

```python
class Backend:

    async def keys_match(self, pattern: str) -> AsyncIterator[str]:
        ...
```
so there is an error
```
cashews/backends/memory.py:73: error: Return type "AsyncIterator[str]" of "keys_match" incompatible with return type "Coroutine[Any, Any, AsyncIterator[str]]" in supertype "Backend"  [override]
```

but the following solves type hints problems:
```python
    @abstractmethod
    async def keys_match(self, pattern: str) -> AsyncIterator[str]:
        ...
```

**Comment by Krukov** [comment]
I am not sure but maybe we can take a look to Protocols https://peps.python.org/pep-0544/. Can it solve a problem? 
The main point that ABC add runtime checking that is not necessary for typing.

Anyway I think we can add Abstract for  Backend class (ABC)

**Comment by Krukov** [comment]
covered by https://github.com/Krukov/cashews/pull/161
